### ISSUE TITLE
Cannot compile by CMake

### ISSUE THREAD

**Issue by samoxbal** [madf/jwtxx#17]
I'm tried to link library by CMakeLists.txt, but compilation failed with error:

/usr/bin/ld: /usr/local/lib/libjwtxx.a(utils.cpp.o): undefined reference to «X509_free@@OPENSSL_1.0.0»
//lib/x86_64-linux-gnu/libcrypto.so.1.0.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

What's the reason of this error?

**Comment by madf** [comment]
I think you either missed -lcrypto or put it before -ljwtxx. Please check the order of your libraries.

**Comment by samoxbal** [comment]
I don't set linker options manually, use CMake. Please help me correctly include library in CMakeLists.txt

**Comment by madf** [comment]
I understand. You use something like target_link_libraries — there should be 'jwtxx' and then 'crypto'.
Or just show me your CMakeLists.txt

**Comment by samoxbal** [comment]
Yes, of course. That's my CMakeLists:
[CMakeLists.txt](https://github.com/madf/jwtxx/files/883729/CMakeLists.txt)

**Comment by madf** [comment]
Try adding 'crypto' after "${POCO_LIBS}" in the target_link_libraries.

**Comment by madf** [comment]
Well, you also need Jansson library – it's a JSON parser used in JWTXX. Look at the CMakeLists.txt in 'tools' directory in JWTXX repo.

**Comment by samoxbal** [comment]
Thank you!!! All works great.

**Comment by madf** [comment]
So I can close the issue, right?

**Comment by samoxbal** [comment]
Yes, you can.
