### ISSUE TITLE
Question on sign function using ES256 algorithm

### ISSUE THREAD

**Issue by hellojaewon** [madf/jwtxx#21]
Hello, I have a question the output of sign function using ES256 algorithm.
According to the [RFC 7515](https://tools.ietf.org/html/rfc7515#appendix-A.3.1), the result of the digital signature is the Elliptic Curve (EC) point (R, S), where R and S are unsigned integers. The JWS Signature is the value R || S. When the algorithm is ES256, the length of R || S is 64. However, the jwtxx library produces size of 72(EVP_DigestSignFinal(,.,.&res)). Could you help me? Why the sizes are different?

Thank you in advance. Your lib and codes very helpful for me to understand the JWT.

**Comment by madf** [comment]
You are right about the signature, it's just two 32-byte numbers. But OpenSSL signature is a DER-encoded ASN.1 structure, like the following:
```
ECDSASignature ::= SEQUENCE {
    r   INTEGER,
    s   INTEGER
}
```
DER encoding rules are just the same as BER encoding rules, but a bit more strict. In our case it doesn't matter. BER says that each piece of data is:
```
<type-tag><contents-length><contents>
```
If you look closer to your signature, for example by adding a breakpoint at JWTXX::Keys::PEM::sign, and advancing to the end, you can see two things. First, initial signature buffer length is 72, which is a minimum requirement estimated by EVP_DigestSignFinal. Actual length is 70, you take it after filling the buffer with signature in the last call to the EVP_DigestSignFinal. It is still bigger than 64, eh?

Go further. Let's look at the signature:
```
(gdb) x/70xb block.m_buffer
0x65de90:	0x30	0x44	0x02	0x20	0x35	0x95	0x99	0xd7
0x65de98:	0x19	0x4c	0x48	0xf2	0xd5	0xc9	0x38	0x88
0x65dea0:	0x0c	0x53	0xc8	0x4f	0x49	0x44	0x74	0x45
0x65dea8:	0x9e	0xdf	0x85	0x5e	0x4e	0x63	0x53	0xe5
0x65deb0:	0x58	0xb4	0xeb	0x6a	0x02	0x20	0x65	0x92
0x65deb8:	0x8f	0x65	0x7e	0xb7	0x25	0xb1	0x63	0xc5
0x65dec0:	0x36	0x5f	0xeb	0x80	0x91	0xd9	0xff	0x87
0x65dec8:	0x11	0x38	0xcf	0x1e	0xb9	0xd4	0xd7	0xd6
0x65ded0:	0xc6	0x20	0xbc	0x81	0x15	0xdc
```
Here I ask gdb to e**x**amine **70** **b**ytes of memory in he**x**. It starts from 30 44. 30 is a type-tag for SEQUENCE. 44 in hex is 68 in dec. 68 is a length of the SEQUENCE which contains two INTEGER values tagged as 02 20, where 02 is a type-tag for INTEGER and 20 is the length. 20 in hex is 32 in dec. So here are your two 32-byte unsigned integers. Wrapping back: (32 + 2) * 2 + 2 is 70.

**Comment by madf** [comment]
BTW, here you can find the description of the ASN.1 encoding rules: https://www.itu.int/rec/T-REC-X.690-201508-I/en

**Comment by madf** [comment]
Signature format is defined in the Appendix A of the RFC5480 (look for DSA-Sig-Value): https://www.ietf.org/rfc/rfc5480.txt

**Comment by hellojaewon** [comment]
Yes, actual size was different from initial result from EVP_DigestSignFinal.
However, in my case it was either 70 or 71. Here is the memory layout.
For 70 bytes, the byte sequence structure is same with yours.
`
0x00000000068D8EF0  30 44 02 20 47 e9 f6 09 57 fe 9e ae a2 e6 26 65 5b 4d 94 a0 cd 4b a5 75 19 c4 83 82 cc d7`
`0x00000000068D8F0E  29 dc ab 6e 1a b7 02 20 46 70 88 de 82 c2 5f 5e 87 b2 56 31 34 5a fc 18 e8 8c 30 a6 17 9f`
`0x00000000068D8F2C  fb f2 88 ef f5 79 f0 ac 43 8e`

For 71 bytes,
`0x0000000002FACC40  30 45 02 20 26 ac 83 4f b1 91 59 f4 87 85 3a de 43 5d 8d b7 e3 19 f2 12 df 71 ce 50 26 89`
`0x0000000002FACC5E  ed 91 86 03 83 ab 02 21 00 df d9 da 37 36 94 50 50 34 f1 31 7c 3f d2 54 6b 93 87 82 1f 4c`
`0x0000000002FACC7C  f4 de 8c ab b4 9f 02 ea fb a2 8f`
the byte sequence structure starts with 0x30, 0x45 which is 1 byte larger than above SEQUENCE. The two integers starts with 0x02, 0x21 and 0x02,0x20 sometimes the byte sequences for two INTERGER was reverse. When the length for INTERGER was 0x21, the first byte was always 0x00. That is the same INTERGER if 0x00 was missing.
My compiler environment is VS2013, openssl version is 1.0.1i and SSL_SESSION_ASN1_VERSION is 0x0001 which is defined in <openssl/ssl.h> header file.

I really appreciate your detailed explanations and the references, too.

**Comment by madf** [comment]
That's an interesting observation. Have you found a reason for this one extra byte? Can you provide your JWT header and payload?

**Comment by hellojaewon** [comment]
I'm using ES256 algorithm to send push message via [APNs API](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html). The JWT header and claims set are as follows.
`{
    "alg": "ES256",
    "kid": "ABC123DEFG"
}`
`{
    "iss": "DEF123GHIJ",
    "iat": 1437179036
 }`

However, I didn't find what this one extra byte is. I'll comment on it, if I found the reason.
Thank you.
