### ISSUE TITLE
Expiration

### ISSUE THREAD

**Issue by stellanhaglund** [madf/jwtxx#25]
Hi, i cant find any examples where the token has an expiration part of it or a custom payload, how would that look?

**Comment by madf** [comment]
You can use unit tests as examples, like here: https://github.com/madf/jwtxx/blob/master/tests/hmactest.cpp#L178

In general, there is a JWTXX::Validate::exp validator which takes a time_t as an argument  and validates the token against this time. By default it takes current time.

Full list of validators is here: https://madf.github.io/jwtxx/namespace_j_w_t_x_x_1_1_validate.html

They can be used in JWT constructor and in JWT::verify function. More on this here: https://madf.github.io/jwtxx/class_j_w_t_x_x_1_1_j_w_t.html

**Comment by stellanhaglund** [comment]
Sorry I don't quite get it. :/
But doesn't those tests just compare against a already set expiry?
How would I set an expiry for the token say 1 day from now?

**Comment by madf** [comment]
I see. I misunderstood your question, I tought you were talking about validation, not construction.

Well, there is only one way to construct a token – to pass a collection of pairs to the JWT constructor. According to the standard, expiration is specified by the 'exp' pair whose value is a UNIX timestamp. Unfortunately, pairs are always string, so you need to convert the timestamp from time_t to std::string.

JWT token1(Algorithm::none, {{"iss", "madf"}, {"exp", "1506069061"}});
JWT token2(Algorithm::none, {{"iss", "madf"}, {"exp", std::to_string(time(nullptr) + 86400)}});

1506069061 is a pre-calculated value of "tomorrow", 86400 is a number of seconds in a day.

**Comment by stellanhaglund** [comment]
cool thanks, would I add a custom key value that way to?
I currently use jsonwebtoken for nodejs where I add the uuid and email of the user into the token, would that be like this?
`JWT token(Algorithm::none, {{"iss", "madf"}, {"exp", "1506069061"}, {"uuid", ""}, {"email", ""}});`

**Comment by madf** [comment]
No problems with custom tokens, use whatever you want.

**Comment by stellanhaglund** [comment]
great thanks for your help! really looking forward to use this! 👍

**Comment by madf** [comment]
Anytime! Closing this issue.
