### ISSUE TITLE
invalid signature signing es256 tokens

### ISSUE THREAD

**Issue by mileedev** [madf/jwtxx#28]
The library doesn't seem to produce valid signatures when using the ES256 algorithm.  We have a private/public elliptical curve key pair we use and the produced and verified signature only seem to work internally with the library.

The server we're trying to hit against seems to think the signature is invalid.  Additionally, if I feed in a JWT string produced by a different library, jwtxx seems to think the signature is invalid as well.

**Comment by madf** [comment]
Can you provide an example of such token? I mean, the one produced by a different library.

Also, is the server has public access?

**Comment by madf** [comment]
I took libjwt by Ben Collins (https://github.com/benmcollins/libjwt) and found out that it really produces signatures different from my lib. Apart from normal OpenSSL signing it converts a signature into a different format. Apparently, OpenSSL EVP functions use something other than (r, s) pair. I will look closer to the issue.

There are two things with ECDSA which make things hard:
1. It produces different signatures for the same data.
2. There are virtually no online validators for ES* algorithms.

**Comment by madf** [comment]
OpenSSL generate DER-encoded signatures by default per X9.62. JWT says that ECDSA signatures should be in plain format. I added necessary conversion for both encoding and verification. The library should be compatible now. Checked with pyjwt.

**Comment by madf** [comment]
Use version 1.1.8.
