### ISSUE TITLE
"invalid_grant" issue while creating the token

### ISSUE THREAD

**Issue by Ar-Haripriya** [madf/jwtxx#32]
After creating JWT::Token, sending the request to oauth2.googleapis to get the Access Token. But request failing with the following error response. **Response: {"error":"invalid_grant","error_description":"Invalid grant: account not found"}**

**Comment by madf** [comment]
I never used this library with googleapis. Can you provide more information: how exactly do you construct the token, what claims do you use?

Also, note that this library is limited to string-value claims. It may not work with strict APIs. See #29 and #26

**Comment by Ar-Haripriya** [comment]
Pairs header = {{"iss", "XXXXX"},
		{"sub", "XXXXX"},
		{"aud", "XXXXX"},
		{"iat", iatString},
		{"exp", expString}};

	Pairs claims = {{"scope", "XXXXX"}};
	
	JWT jwt(Algorithm::RS256,  claims, header);

	string token = jwt.token("secret_key.pem" ,[](){ return "123456"; });


Used the above headers and claims to generate the JWT. 
The generated JWT is used to send CURL request to googleapis to get the Access Token.
The following error is resulted in the CURL response.
Response: {"error":"invalid_grant","error_description":"Invalid grant: account not found"}

**Comment by Ar-Haripriya** [comment]
Thank You. It worked. Received the Access Token.
But how to set iat and exp with the current time value.

**Comment by Ar-Haripriya** [comment]
iat and exp are worked with the following code. 

	std::stringstream iatss;
    iatss << std::time(nullptr);
    std::string iatStr = iatss.str();

	std::stringstream expss;
    expss << (std::time(nullptr) + 3600);
    std::string expStr = expss.str();

Thanks for the immediate support.

**Comment by madf** [comment]
Instead of `std::stringstream` it's better to use `std::to_string`.
